Sentinel Reporting
DARTSG/moodler pull request #66
Opened 2024-09-23 08:25 UTC by AngPeiHao

**Description:** Added two API calls for sentinel reporting.

1.  `gradereport_user_get_grade_items`
Get the gradereport of the course from the LMS.

2. `get_students_raw()`
Get the raw result of `core_enrol_get_enrolled_users`.

**Ticket:** [Link to the ticket](https://dartsg.atlassian.net/jira/software/projects/LTI/boards/38?selectedIssue=LTI-307)

**Author Concerns:**
The output of `get_students()` is a dictionary that maps the user id to the user full name. The report of Sentinel require more information from the students. Changing the implementation of `get_students()` will require many other changes.

2024-10-21 06:10 UTC, achmadridzwan requested changes

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +            course_name = course_name_match["course_name"]
```suggestion
            course_name = parse(course_name_format, full_name).get("course_name")

            if course_name is None:
                continue
```

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +def get_exercises_by_topic(courseid: int) -> Dict[str, List[Dict[str, int | str]]]:
Create a serializer for clearer typing and easier future maintenance

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +    }
not needed if serializer is created

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +        # Ignore topics with no exercises
```suggestion
        # Ignore topics with no modules
```

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +def get_exercises(courseid: int) -> List[Dict[str, int | str]]:
same as comment above regarding creating serializer

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/groups.py
> +def get_student_map(course_id: int):
Create serializer to parse the student map data that is returned for easier reference in elsewhere that use this `get_student_map` function

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +    ]
Based on `exercises_by_topic[topic]`, I'm assuming `exercises_by_topic` is a dict

```suggestion
    exercises = []
    for topic, exercises_list in test.items():
         exercises.extend(exercises_list)
     return exercises
```

2024-10-21 06:10 UTC, achmadridzwan commented on moodler/sections.py
> +    ]
Refrain from double for loop as much as possible

2024-10-21 07:12 UTC, achmadridzwan commented on moodler/report.py
> +    response = call_moodle_api("gradereport_user_get_grade_items", courseid=courseid)
Error handling not required?

2024-10-21 07:12 UTC, achmadridzwan commented on moodler/students.py
> +        for user in core_enrol_get_enrolled_users(courseid)
What happens if api call does not return required data? i.e. error

2024-10-21 07:12 UTC, achmadridzwan commented on moodler/sections.py
> +    course_content = core_course_get_contents(courseid)
What happens if api call does not return required data? i.e. error

2024-10-23 02:06 UTC, AngPeiHao commented on moodler/sections.py
> +            course_name = course_name_match["course_name"]
`parse` function returns a Result object which does not have the `get` method.

The purpose of the check is to ensure that there is a result from `course_name_match` before retrieving the `course_name` from the result to handle a `TypeError` when `parse` returns a None object when there is no match.

2024-10-23 02:29 UTC, AngPeiHao commented on moodler/sections.py
> +def get_exercises(courseid: int) -> List[Dict[str, int | str]]:
Would it be enough if its `List[Exercise]`?

2024-10-23 03:29 UTC, AngPeiHao commented on moodler/groups.py
> +def get_student_map(course_id: int):
Renamed function to `get_students_with_groups`

2024-10-24 09:14 UTC, achmadridzwan commented on moodler/sections.py
> +            course_name = course_name_match["course_name"]
Got it. You mentioned a `Result` object is returned from `parse`. Should `course_name` be accessed via `course_name_match.course_name` then?

2024-10-24 09:14 UTC, achmadridzwan commented on moodler/sections.py
> +def get_exercises(courseid: int) -> List[Dict[str, int | str]]:
Yup better

2024-10-25 03:06 UTC, achmadridzwan approved these changes

2024-10-28 02:04 UTC, AngPeiHao commented on moodler/sections.py
> +            course_name = course_name_match["course_name"]
The `Result` object that is returned from `parse` looks something like `<Result () {'course_name': 'Introduction to Web Development'}>` and `course_name_match.course_name` will raise an `AttributeError`.

2024-11-06 08:50 UTC, merged